import type { NextPage } from "next";
import Head from "next/head";
//"--version 1.7.6 alpha" next bug header animation
import Image from "next/image";
import index from "../styles/Index.module.css";
//
import Carousel from "../components/carousel/carousel";
//
import { multilingualism } from "../contexts/multilingualism";
import { useContext } from "react";
//
const Home: NextPage = () => {
  const { words } = useContext(multilingualism);
  return (
    <div className={index.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={index.main}>
        <div className={index.secondMain}>
          <div className={index.carouselContainer}>
            <div className={index.illustrationDolphinDeco}>
              <Image
                src="/illustrationDolphin/dolphin.png"
                height={150}
                width={150}
                alt="illustration dolphin svg"
              />
            </div>
            <Carousel /> {/*main carousel*/}
            <div className={index.carouselDescription}>
              <p>{words?.carouselDescription}</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
